# Category.create!(:title => "Missed Connections")
# Category.create!(:title => "Squirrel Seeking Chipmunk")
# Category.create!(:title => "Nuts 4 Sale")
# Category.create!(:title => "Find a Fox")

Post.update(1, :description => "IF YOU NEED AN ARCTIC FOX IVE GOT THEM BY THE FLEET STOP BY ANYTIME NO LOWBALL OFFERS THXXXX", :location => "anywhere", :OMGNSFWROFLYOLOLOLGTFO => false)
Post.update(2, :description => "good quality silver fox available immediately nothing wrong with him just no longer have much use or time because I have gotten very busy with work LOL you know how it is LOLOLOLOL!!! but srsly he is very good looking you will get lots of stares with this fox!! his name is george", :location =>"foxtown", :OMGNSFWROFLYOLOLOLGTFO => false)
Post.update(3, :description => "hey squirrel i liked the way you flicked your tail when you were listening to that bird did you think it was an owl dont worry baby im not a predator but i would like to swoop in and carry you home with me", :location => "the big park with that weird spiky grass", :OMGNSFWROFLYOLOLOLGTFO => true)
Post.update(4, :description => "it was big and shiny and i dunno why you dropped such a tantalizing acorn maybe you were trying to get my attention well squirrel it worked baby CALL ME LOL <wink>", :location => "the beach", :OMGNSFWROFLYOLOLOLGTFO => false)

Post.create!(:title => "FREE TO GOOD HOME fire fox", :location => "downtown", :price => 0, :description => "BEFORE YOU ASK this is not a firefox it is just a fox that for some reason likes to start fires I don't know what it wrong with her but I can't keep her anymore my landlord is threatening legal action and I don't want to have to leave her somewhere in the woods.", :category_id => 4, :OMGNSFWROFLYOLOLOLGTFO => false)
Post.create!(:title => "LOOKING FOR FOXES? WE GOT FOXES!" :location => "anyware", :description => "WE HAVE LOTS OF FOXES ALL KINDS EVERY KIND ANY KIND YOU WANT IF WE DON'T GOT IT WE CAN GET IT COME FIND VINNY JUST ASK AROUND EVERYONE KNOWS ABOUT VINNY PRICES STARTING AT $700 OR WILL BARTER FOR MACADAMIAS", :category_id => 4, price: 1, :OMGNSFWROFLYOLOLOLGTFO => false)
Post.create!(:title => , :location => , :description => "", :category_id => 1, :OMGNSFWROFLYOLOLOLGTFO => false)
Post.create!(:title => "unroasted brazils and filberts", :location => "downtown", :price => 20, :description => "", :category_id => 3, :OMGNSFWROFLYOLOLOLGTFO => false)
Post.create!(:title => "honey roasted almonds", :location => "small park by the school" , :price => 100, :description => "best almonds in the world no really you will never find almonds like these again they are very exotic rare brand cerulean quartz $100 OBO", :category_id => 3, :OMGNSFWROFLYOLOLOLGTFO => false)

# Post.create!(:title => "You dropped your acorn by the lake", :location => , :price => 50.75, :description => "", :category_id => 3, :OMGNSFWROFLYOLOLOLGTFO => false)
# Post.create!(:title => "You dropped your acorn by the lake", :location => , :description => "", :category_id => 2, :OMGNSFWROFLYOLOLOLGTFO => false)
Post.create!(:title => "S4C - 24 wks", :location =>"school yard" , :description => "new in town looking for a tree mate just someone to hang out with you know how it is LOL!", :category_id => 2, :OMGNSFWROFLYOLOLOLGTFO => false)
# Post.create!(:title => "You dropped your acorn by the lake", :location => , :description => "", :category_id => 2, :OMGNSFWROFLYOLOLOLGTFO => false)
# Post.create!(:title => "You dropped your acorn by the lake", :location => , :description => "", :category_id => 4, :OMGNSFWROFLYOLOLOLGTFO => false)
# Post.create!(:title => "You dropped your acorn by the lake", :location => , :description => "", :category_id => 4, :OMGNSFWROFLYOLOLOLGTFO => false)
# Post.create!(:title => "You dropped your acorn by the lake", :location => , :description => "", :category_id => 4, :OMGNSFWROFLYOLOLOLGTFO => false)